galaxy_info:
  author: DevOps Department
  description: Traefik Setup
  company: ""
  role_name: traefik
  namespace: traefik
  license: MIT

  min_ansible_version: "2.14"

  platforms:
    - name: Ubuntu
      versions:
        - noble

  galaxy_tags:
    - traefik

dependencies: []
