[router_servers]
router-1 ansible_host=10.10.1.254

[lb_servers]
lb-1 ansible_host=10.10.1.2

[app_servers]
app-1 ansible_host=10.10.2.2

[postgres_servers]
db-1 ansible_host=10.10.3.2

[docker_servers]
lb-1 ansible_host=10.10.1.2
app-1 ansible_host=10.10.2.2
db-1 ansible_host=10.10.3.2

# Do Not Add Anything After This Line
[proxyed_servers:children]
app_servers
postgres_servers

[proxyed_servers:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p -q {{ ansible_user }}@10.10.1.254"'
