galaxy_info:
  author: DevOps Department
  description: Docker Setup
  company: ""
  role_name: docker
  namespace: docker
  license: MIT

  min_ansible_version: "2.14"

  platforms:
    - name: Ubuntu
      versions:
        - noble

  galaxy_tags:
    - docker

dependencies: []
